version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic-cms
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8080}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Uncomment if you want to include a development environment
  # app-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development-dependencies-env
  #   container_name: traffic-cms-dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8080}
  #   command: npm run dev 