name: Create Jira Ticket for Opened Issue

on:
  # Will trigger the workflow when a new issue is opened
  issues:
    types: opened

jobs:
  create_jira_ticket:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # Authenticate with Jira first
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: GA
          issuetype: Bug
          summary: ${{ github.event.issue.title }}
          description: ${{ github.event.issue.body }}
      
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
